# Generated by Django 5.2.6 on 2025-09-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPerfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('lancamento', models.DateField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='perfumes/')),
                ('nota_media', models.FloatField(default=0.0)),
                ('familia_olfativa', models.CharField(blank=True, max_length=100, null=True)),
                ('estilo', models.CharField(blank=True, max_length=100, null=True)),
                ('intensidade', models.CharField(blank=True, max_length=50, null=True)),
                ('fixacao', models.CharField(blank=True, max_length=50, null=True)),
                ('links', models.ManyToManyField(blank=True, related_name='perfumes', to='perfumes.linkperfume')),
                ('notas_cabeca', models.ManyToManyField(blank=True, related_name='perfumes_cabeca', to='perfumes.nota')),
                ('notas_corpo', models.ManyToManyField(blank=True, related_name='perfumes_corpo', to='perfumes.nota')),
                ('notas_fundo', models.ManyToManyField(blank=True, related_name='perfumes_fundo', to='perfumes.nota')),
            ],
        ),
    ]
