# Generated by Django 5.2.6 on 2025-09-05 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DupePesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similaridade', models.FloatField(blank=True, null=True)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfumes.perfume')),
            ],
        ),
    ]
